#!/bin/bash

# 設施圖標更新測試腳本

echo "======================================"
echo "設施圖標更新 - 檢查清單"
echo "======================================"
echo ""

echo "✓ 1. 資料庫 schema 已更新 (facilities.icon 欄位)"
echo "✓ 2. 種子資料已包含 Lucide 圖標名稱"
echo "✓ 3. API (api.ts) 已更新取得 icon 欄位"
echo "✓ 4. DataStore 類型已包含 icon 欄位"
echo "✓ 5. MapView 改用 SVG 圖標"
echo "✓ 6. MapPage 直接使用資料庫的 icon 值"
echo "✓ 7. 已移除 mapFacilityIcon 轉換函數"
echo ""

echo "======================================"
echo "需要執行的操作"
echo "======================================"
echo ""
echo "1. 更新資料庫："
echo "   方法 A (開發): supabase db reset"
echo "   方法 B (生產): psql ... -f supabase/migrations/add_facility_icons.sql"
echo ""
echo "2. 重新啟動開發伺服器："
echo "   cd web && pnpm dev"
echo ""
echo "3. 測試地圖："
echo "   - 開啟地圖頁面"
echo "   - 確認設施顯示圖標而非文字"
echo "   - 點擊設施確認資訊卡顯示"
echo ""

echo "======================================"
echo "圖標對應"
echo "======================================"
echo ""
echo "公園/遊戲場    → TreeDeciduous (樹木)"
echo "路燈          → Lightbulb (燈泡)"
echo "警察局        → ShieldCheck (盾牌)"
echo "人行道        → Footprints (腳印)"
echo "樂齡中心      → HeartHandshake (愛心握手)"
echo "飲水機        → Droplets (水滴)"
echo "校園周邊      → School (學校)"
echo "道路坑洞      → Construction (施工)"
echo ""
